### ISSUE TITLE
Need Example

### ISSUE THREAD

**Issue by Adityamalladi** [finnjohnsen/BitlyAndroid#1]
Hi,

I am very new to Bitly. I don't know how to use it. I am developing a Android chatting app So that i want to send bitly url to install app if they don't have my app in their phones, or i want to open app if installed.

Please help me with example.

**Comment by finnjohnsen** [comment]
I've not touched this code in years. You'll just have to pull it and run the tests and see if it still works with the current Bit.ly API version.
